company_whitelist = {
    'Tech Firefly': None,
    'TruFusion': None,
    'Keywords Studios': None,
    'Leading Path Consulting': None,
    'CXG': None,
    'The PAC Group': None,
    'Crowd Favorite': None,
    'Circuitronix': None,
    'Happy.Rentals': None,
    'MassMutual Carolinas': None,
    'Movinmotion': None,
    'Tiger Analytics': None,
    'Ryanair': None,
    'West Wing Writers': None,
    'Dentons': None,
    'AgileMD': None,
    'Gram Games': None,
    'DemandLab': None,
    'Black Spectacles': None,
    'Nitor': None,
    'Solar Alternatives': None,
    'Deeproute.ai': None,
    'Vela Games': None,
    'Provado Health': None,
    'GuardSight': None,
    'ProgressSoft': None,
    'SmartLabs': None,
    'Electric Square': None,
    'aptihealth': None,
    'Assembly': None,
    'DataVisor': None,
    'HyperVerge': None,
    'ASUS Robotics & AI Center': None,
    'Zengistics': None,
    'Oura': None,
    'Qoala': None,
    'Motorsport Games': None,
    'Procure Ai': None,
    'Kantox': None,
    'Quadrant': None,
    'Fable': None,
    'Portfolio BI': None,
    'Inbox Health': None,
    'AlphaStream.io': None,
    'iGenius': None,
    'Autofleet': None,
    'Hugging Face': None,
    'Foundry': None,
    'LegalMatch.com': None,
    'Applied EV': None,
    'Limbic': None,
    'Ride Health': None,
    'Genetec': None,
    'Koala': None,
    'Redox': None,
    'Lawyer.com': None,
    'PayEngine': None,
    'Paro.ai': None,
    'Imagine.io': None,
    'Sequel.io': None,
    
    'Vasion': None,
    'Rokt': None,
    'Outdoorsy': None,
    'TetraScience': None,
    'Athletic Greens': None,
    'Stellar Cyber': None,
    'IO Global': None,
    'Nuvei': None,
    'Paytrix': None,
    'ArchiPro': None,
    'Quantexa': None,
    'Hike': None,
    'Bitget': None,
    'Yapily': None,
    'GoHenry': None,
    'Keeper Security, Inc.': 'Keeper Security',
    'Starling Bank': None,
    'Glorify': None,
    'Tiendanube | Nuvemshop': 'Nuvemshop',
    'Let\'s Do This': None,
    'Zone & Co': None,
    'Cars24': None,
    '9fin': None,
    'Sinch': None,
    'QuintoAndar': None,
    'Builder.ai - What would you Build?': 'Builder.ai',
    'Blackbird.AI': 'Blackbird AI',
    'Reliance Health': None,
    'Epignosis': None,
    'Neo Financial': None,
    'Satispay': None,
    'Moladin': None,
    'Motorway': None,
    'Akur8': None,
    'Idoven': None,
    'Skedulo': None,
    'Blink': None,
    'Lightyear': None,
    'ResortPass': None,
    'Beam': None,
    'Apna': None,
    'LingoAce': None,
    'FairMoney': None,
    'Hex Trust': None,
    'Amogy': None,
    'Semios': None,
    'Boohoo Group': None,
    'ColdQuanta': None,
    'Exotec': None,
    'Project Canary': None,
    'Preferred Networks': None,
    'Clarity AI': None,
    'Sharegain': None,
    'Paro': None,
    'Evolv': None,
    'DroneUp': None,
    'EquityBee': None,
    'Bibit': None,
    'TileDB': None,
    'Gigs': None,
    'Axelar': None,
    'Universal Quantum': None,
    'Constructor': None,
    'All.Space': None,
    'Zoomo': None,
    'Precision Neuroscience': None,
    'Money Fellows': None,
    'Shift4': None,
    'Persado': None,
    'Ieso': None,
    'Insite': None,
    'Prophecy': None,
    'Employment Hero': None,
    'Aldrin': None,
    'Workable': None,
    'Kuda': None,
    'Fortanix': None,
    'Foodics': None,
    'Quizizz': None,
    'Tavus': None,
    'Lightmatter': None,
    'Intuition Machines': None,
    '10x': None,
    'Proxymity': None,
    'Ajaib': None,
    'Heartex': None,
    'Sky Mavis': None,
    'Clerk': None,
    'Entain': None,
    'Spatial': None,
    'ICEYE': None,
    'Carbyne': None,
    'Island': None,
    'Tresata': None,
    'stakefish': None,
    'Eleos Health': None,
    'Perceptyx': None,
    'BetterHelp': None,
    'ReversingLabs': None,
    'Oxbotica': None,
    'Inspectorio': None,
    'LearnWorlds': None,
    'ProducePay': None,
    'Freelancer.com': None,
    'Elvie': None,
    'Smart': None,
    'Square Enix': None,
    'Spenmo': None,
    'Finexio': None,
    'Entropik': None,
    'Bitstamp': None,
    'FundamentalVR': None,
    'Perlego': None,
    'Kroo': None,
    'TransferMate': None,
    'SirionLabs': None,
    'Measurabl': None,
    'Oxford Quantum': None,
    'Medwing': None,
    'Hack the Box': None,
    'Tado': None,
    'Shares': None,
    'Eterlast': None,
    'Vertice': None,
    'Carry1st': None,
    'Sary': None,
    'AvantStay': None,
}
