# Generated by Django 4.0.5 on 2022-07-04 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='employerSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.employersize'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='closeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.country'),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='isFullTime',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='isRemote',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='jobDepartment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='openDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='referralBonus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='salaryCeiling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='salaryFloor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.state'),
        ),
    ]
