# Generated by Django 4.0.5 on 2022-06-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jobvineuser',
            managers=[
            ],
        ),
    ]
