# Generated by Django 4.0.5 on 2022-07-06 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jvapp.models._customDjangoField


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0003_socialplatform_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinkFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('cities', jvapp.models._customDjangoField.SeparatedValueField('|', blank=True, max_length=500, null=True)),
                ('countries', models.ManyToManyField(to='jvapp.country')),
                ('departments', models.ManyToManyField(to='jvapp.jobdepartment')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jvapp.employer')),
                ('jobs', models.ManyToManyField(to='jvapp.employerjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.socialplatform')),
                ('states', models.ManyToManyField(to='jvapp.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='jobDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.jobdepartment'),
        ),
    ]
