# Generated by Django 4.0.5 on 2022-07-06 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0004_jobdepartment_sociallinkfilter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinkfilter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
