# Generated by Django 4.0.5 on 2022-07-11 04:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0005_alter_sociallinkfilter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=75, null=True)),
                ('resume', models.FileField(upload_to='resumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'pages', 'gdoc'])])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=75, null=True)),
                ('resume', models.FileField(upload_to='resumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'pages', 'gdoc'])])),
                ('employer_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='jvapp.employerjob')),
                ('social_link_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_application', to='jvapp.sociallinkfilter')),
            ],
            options={
                'unique_together': {('employer_job', 'email')},
            },
        ),
    ]
