# Generated by Django 4.0.5 on 2022-07-13 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0007_employerpermission_alter_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerauthgroup',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jvapp.employer'),
        ),
        migrations.AlterField(
            model_name='employerpermission',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='employerauthgroup',
            unique_together={('name', 'employer')},
        ),
    ]
