# Generated by Django 4.0.5 on 2022-07-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0010_jobvyneuser_permission_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerpermission',
            name='user_type_bits',
            field=models.SmallIntegerField(default=16),
            preserve_default=False,
        ),
    ]
