# Generated by Django 4.0.5 on 2022-07-13 04:01

from django.db import migrations

from jvapp.utils.migration_permissions import update_permissions


class Migration(migrations.Migration):
    dependencies = [
        ('jvapp', '0012_employerauthgroup_user_type_bit'),
    ]
    
    operations = [
        migrations.RunPython(update_permissions, atomic=True),
    ]
