# Generated by Django 4.0.5 on 2022-07-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0011_employerpermission_user_type_bits'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerauthgroup',
            name='user_type_bit',
            field=models.SmallIntegerField(default=16),
            preserve_default=False,
        ),
    ]
