# Generated by Django 4.0.5 on 2022-07-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0012_add_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='is_employer_deactivated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
