# Generated by Django 4.0.5 on 2022-07-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0013_jobvyneuser_is_employer_deactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_dt', models.DateTimeField()),
            ],
        ),
    ]
