# Generated by Django 4.0.5 on 2022-07-22 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0014_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_url', models.CharField(max_length=100)),
                ('filter_id', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('access_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('region', models.CharField(blank=True, max_length=60, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('browser', models.CharField(blank=True, max_length=60, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=20, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=30, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('device_brand', models.CharField(blank=True, max_length=40, null=True)),
                ('device_model', models.CharField(blank=True, max_length=40, null=True)),
                ('is_mobile', models.BooleanField(blank=True, null=True)),
                ('is_tablet', models.BooleanField(blank=True, null=True)),
                ('is_pc', models.BooleanField(blank=True, null=True)),
                ('is_bot', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
