# Generated by Django 4.0.5 on 2022-07-22 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0015_pageview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='filter_id',
        ),
        migrations.AddField(
            model_name='pageview',
            name='social_link_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_view', to='jvapp.sociallinkfilter'),
        ),
    ]
