# Generated by Django 4.0.5 on 2022-07-26 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0017_employerfiletag_employerfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('header', models.CharField(max_length=250)),
                ('orderIdx', models.SmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=15)),
                ('item_parts', models.JSONField()),
            ],
            options={
                'ordering': ('-orderIdx',),
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employer',
            name='modified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerfile',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerfile',
            name='modified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='modified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('is_viewable', models.BooleanField(default=False)),
                ('content_item', models.ManyToManyField(to='jvapp.contentitem')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_page', to='jvapp.employer', unique=True)),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
