# Generated by Django 4.0.5 on 2022-07-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0018_contentitem_employer_created_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='header',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
