# Generated by Django 4.0.5 on 2022-07-27 17:14

import django.core.validators
from django.db import migrations, models
import jvapp.models.employer
import jvapp.models.job_seeker


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0019_alter_contentitem_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ('orderIdx',)},
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='employerName',
            new_name='employer_name',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='employerSize',
            new_name='employer_size',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='description',
        ),
        migrations.AddField(
            model_name='employer',
            name='color_accent',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='color_primary',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='color_secondary',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=jvapp.models.employer.get_employer_upload_location),
        ),
        migrations.AlterField(
            model_name='employerfile',
            name='file',
            field=models.FileField(upload_to=jvapp.models.employer.get_employer_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'gif', 'mp4', 'm4v', 'mov', 'wmv', 'avi', 'mpg', 'webm', 'doc', 'docx', 'pdf', 'txt', 'rtf'])]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to=jvapp.models.job_seeker.get_user_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'txt', 'rtf'])]),
        ),
        migrations.AlterField(
            model_name='jobapplicationtemplate',
            name='resume',
            field=models.FileField(upload_to=jvapp.models.job_seeker.get_user_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'txt', 'rtf'])]),
        ),
    ]
