# Generated by Django 4.0.5 on 2022-07-27 17:14

from django.db import migrations

from jvapp.utils.migration_permissions import update_permissions


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0020_alter_contentitem_options_and_more'),
    ]

    operations = [
        migrations.RunPython(update_permissions, atomic=True)
    ]
