# Generated by Django 4.0.5 on 2022-07-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0021_contentitem_config_alter_contentitem_item_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvyneuser',
            name='user_type_bits',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
