# Generated by Django 4.0.5 on 2022-08-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0022_alter_jobvyneuser_user_type_bits'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email_domains',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
