# Generated by Django 4.0.5 on 2022-08-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0023_employer_email_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='business email address'),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='is_business_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
