# Generated by Django 4.0.5 on 2022-08-03 14:37

from django.db import migrations, models
import jvapp.models.user
from jvapp.utils.migration_permissions import update_permissions


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0026_jobvyneuser_profile_picture'),
    ]

    operations = [
        migrations.RunPython(update_permissions, atomic=True),
    ]
