# Generated by Django 4.0.5 on 2022-08-03 14:37

from django.db import migrations, models
import jvapp.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0025_userunknownemployer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=jvapp.models.user.getUserUploadLocation),
        ),
    ]
