# Generated by Django 4.0.5 on 2022-08-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0026_add_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvyneuser',
            name='user_type_bits',
            field=models.SmallIntegerField(default=0),
        ),
    ]
