# Generated by Django 4.0.5 on 2022-08-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0028_remove_jobvyneuser_permission_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployerpermissiongroup',
            name='is_employer_approved',
            field=models.BooleanField(default=False),
        ),
    ]
