# Generated by Django 4.0.5 on 2022-08-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0029_useremployerpermissiongroup_is_employer_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employerjob',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_remote', models.BooleanField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.state')),
            ],
            options={
                'unique_together': {('is_remote', 'city', 'state', 'country')},
            },
        ),
        migrations.RemoveField(
            model_name='employerjob',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employerjob',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employerjob',
            name='isRemote',
        ),
        migrations.RemoveField(
            model_name='employerjob',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employerjob',
            name='state',
        ),
        migrations.AddField(
            model_name='employerjob',
            name='locations',
            field=models.ManyToManyField(to='jvapp.location'),
        ),
    ]
