# Generated by Django 4.0.5 on 2022-08-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0031_rename_countryname_country_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinkfilter',
            options={'ordering': ('-modified_dt',)},
        ),
    ]
