# Generated by Django 4.0.5 on 2022-08-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0033_city_remove_sociallinkfilter_cities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='napme',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('is_remote', 'city', 'state', 'country')},
        ),
    ]
