# Generated by Django 4.0.5 on 2022-08-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0035_currency_employerreferralbonusrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerreferralbonusrule',
            name='order_idx',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='employerreferralbonusrule',
            unique_together={('employer', 'order_idx')},
        ),
    ]
