# Generated by Django 4.0.5 on 2022-08-14 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0037_alter_employerreferralbonusrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='default_bonus_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='default_bonus_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employer_default', to='jvapp.currency'),
        ),
        migrations.AddField(
            model_name='employer',
            name='maximum_bonus_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='maximum_bonus_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employer_maximum', to='jvapp.currency'),
        ),
    ]
