# Generated by Django 4.0.5 on 2022-08-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0038_employer_default_bonus_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerReferralBonusRuleModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('start_days_after_post', models.SmallIntegerField()),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jvapp.currency')),
                ('referral_bonus_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to='jvapp.employerreferralbonusrule')),
            ],
            options={
                'ordering': ('referral_bonus_rule', 'start_days_after_post'),
            },
        ),
    ]
