# Generated by Django 4.0.5 on 2022-08-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0039_employerreferralbonusrulemodifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerreferralbonusrulemodifier',
            name='currency',
        ),
    ]
