# Generated by Django 4.0.5 on 2022-08-16 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0040_remove_employerreferralbonusrulemodifier_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='maximum_bonus_amount',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='maximum_bonus_currency',
        ),
    ]
