# Generated by Django 4.0.5 on 2022-08-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0041_remove_employer_maximum_bonus_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='referral_bonus_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jvapp.currency'),
        ),
    ]
