# Generated by Django 4.0.5 on 2022-08-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0042_employerjob_referral_bonus_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='referral_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='referral_bonus_currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='jvapp.currency', to_field='name'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='referral_bonus_details',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
