# Generated by Django 4.0.5 on 2022-08-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0043_jobapplication_referral_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='default_bonus_currency',
        ),
        migrations.RemoveField(
            model_name='employerjob',
            name='referral_bonus_currency',
        ),
        migrations.RemoveField(
            model_name='employerreferralbonusrule',
            name='bonus_currency',
        ),
    ]
