# Generated by Django 4.0.5 on 2022-08-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0044_remove_employer_default_bonus_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='default_bonus_currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='jvapp.currency', to_field='name'),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='referral_bonus_currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='jvapp.currency', to_field='name'),
        ),
        migrations.AddField(
            model_name='employerreferralbonusrule',
            name='bonus_currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='jvapp.currency', to_field='name'),
        ),
    ]
