# Generated by Django 4.0.5 on 2022-08-22 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0046_usersocialcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialcredential',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersocialcredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_credential', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersocialcredential',
            unique_together={('user', 'provider', 'email')},
        ),
    ]
