# Generated by Django 4.0.5 on 2022-08-24 19:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract
import jvapp.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0048_socialcontentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=jvapp.models.user.getUserUploadLocation, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'gif', 'mp4', 'm4v', 'mov', 'wmv', 'avi', 'mpg', 'webm', 'doc', 'docx', 'pdf', 'txt', 'rtf'])])),
                ('title', models.CharField(max_length=100)),
                ('tags', models.ManyToManyField(to='jvapp.employerfiletag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
    ]
