# Generated by Django 4.0.5 on 2022-08-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0049_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='tags',
        ),
    ]
