# Generated by Django 4.0.5 on 2022-08-28 20:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract
import jvapp.models.content


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0050_remove_userfile_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('content', models.TextField()),
                ('formattedContent', models.TextField()),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_post', to='jvapp.employer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
        migrations.CreateModel(
            name='SocialPostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=jvapp.models.content.get_post_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'm4v', 'mov', 'wmv', 'avi', 'mpg', 'webm', 'png', 'jpeg', 'jpg', 'gif'])])),
                ('social_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jvapp.socialpost')),
            ],
        ),
    ]
