# Generated by Django 4.0.5 on 2022-08-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0051_socialpost_socialpostfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpost',
            old_name='formattedContent',
            new_name='formatted_content',
        ),
    ]
