# Generated by Django 4.0.5 on 2022-08-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0052_rename_formattedcontent_socialpost_formatted_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialpost',
            options={'ordering': ('created_dt',)},
        ),
        migrations.AlterField(
            model_name='socialpostfile',
            name='social_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='jvapp.socialpost'),
        ),
    ]
