# Generated by Django 4.0.5 on 2022-08-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0054_alter_socialpost_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPostAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('platform', models.CharField(max_length=20)),
                ('posted_dt', models.DateTimeField()),
                ('social_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='jvapp.socialpost')),
            ],
        ),
    ]
