# Generated by Django 4.0.5 on 2022-08-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0055_socialpostaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialpostaudit',
            options={'ordering': ('-posted_dt',)},
        ),
    ]
