# Generated by Django 4.0.5 on 2022-08-31 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0056_alter_socialpostaudit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='social_platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jvapp.socialplatform'),
            preserve_default=False,
        ),
    ]
