# Generated by Django 4.0.5 on 2022-09-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0057_socialpost_social_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_post', to='jvapp.socialpost'),
        ),
    ]
