# Generated by Django 4.0.5 on 2022-09-02 20:34

from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0058_socialpost_original_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerAts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('api_key', models.CharField(max_length=50)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_cfg', to='jvapp.employer')),
            ],
            options={
                'unique_together': {('employer', 'name')},
            },
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
    ]
