# Generated by Django 4.0.7 on 2022-09-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0059_employerats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerjob',
            name='is_full_time',
        ),
        migrations.AddField(
            model_name='employerjob',
            name='ats_job_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='employment_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
