# Generated by Django 4.0.7 on 2022-09-03 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0060_remove_employerjob_is_full_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='salary_currency',
            field=models.ForeignKey(blank=True, default='USD', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job', to='jvapp.currency', to_field='name'),
        ),
    ]
