# Generated by Django 4.0.7 on 2022-09-05 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0062_location_latitude_location_longitude_locationlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ats_application_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='UserEmployerCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_candidate_key', models.CharField(max_length=30)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jvapp.employer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'employer')},
            },
        ),
    ]
