# Generated by Django 4.0.7 on 2022-09-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0063_jobapplication_ats_application_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerats',
            name='employment_type_field_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employerats',
            name='job_stage_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerats',
            name='salary_range_field_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
