# Generated by Django 4.0.7 on 2022-09-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0067_useremployeeprofilequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='is_profile_viewable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useremployeeprofileresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_response', to=settings.AUTH_USER_MODEL),
        ),
    ]
