# Generated by Django 4.0.7 on 2022-09-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0068_jobvyneuser_is_profile_viewable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='is_employer_owner',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
