# Generated by Django 4.0.7 on 2022-09-27 16:36

from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0070_employer_billing_email_employer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_key', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('employee_seats', models.PositiveIntegerField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='jvapp.employer')),
            ],
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
    ]
