# Generated by Django 4.0.7 on 2022-10-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0071_employersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_jobs_page_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
