# Generated by Django 4.0.7 on 2022-10-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0072_employer_company_jobs_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='has_employee_seat',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
