# Generated by Django 4.0.7 on 2022-10-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0073_jobvyneuser_has_employee_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='notification_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
