# Generated by Django 4.0.7 on 2022-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0074_employer_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='application_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
