# Generated by Django 4.0.7 on 2022-10-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0075_employerjob_application_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='is_scraped',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
