# Generated by Django 4.0.7 on 2022-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0076_employerjob_is_scraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdepartment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
