# Generated by Django 4.0.7 on 2022-10-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0077_alter_jobdepartment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='stripe_customer_key',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employersubscription',
            name='stripe_key',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
