# Generated by Django 4.0.7 on 2022-11-15 23:02

from django.db import migrations, models
import django.db.models.deletion

from jvapp.models.job_seeker import JobApplication
from jvapp.models.tracking import PageView


def update_platforms(apps, schema_editor):
    job_apps = JobApplication.objects.select_related('social_link_filter', 'social_link_filter__platform').all()
    for job_app in job_apps:
        job_app.platform = job_app.social_link_filter.platform
    JobApplication.objects.bulk_update(job_apps, ['platform'])
    page_views = PageView.objects.select_related('social_link_filter', 'social_link_filter__platform').all()
    for page_view in page_views:
        page_view.platform = page_view.social_link_filter.platform
    PageView.objects.bulk_update(page_views, ['platform'])


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0078_alter_employer_stripe_customer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.socialplatform'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.socialplatform'),
        ),
        # migrations.RunPython(update_platforms, atomic=True),
    ]
