# Generated by Django 4.0.7 on 2022-11-15 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0079_remove_sociallinkfilter_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinkfilter',
            name='platform',
        ),
    ]
