# Generated by Django 4.0.7 on 2022-11-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0080_remove_sociallinkfilter_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinkfilter',
            options={'ordering': ('-is_default', '-modified_dt')},
        ),
        migrations.AddField(
            model_name='sociallinkfilter',
            name='is_default',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='sociallinkfilter',
            name='is_primary',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
