# Generated by Django 4.0.7 on 2022-11-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0081_alter_sociallinkfilter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='auto_day_of_week',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='auto_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='auto_weeks_between',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='is_auto_post',
            field=models.BooleanField(default=False),
        ),
    ]
