# Generated by Django 4.0.7 on 2022-11-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0082_socialpost_auto_day_of_week_socialpost_auto_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='auto_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
