# Generated by Django 4.0.7 on 2022-11-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0083_socialpost_auto_start_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='post_credentials',
            field=models.ManyToManyField(to='jvapp.usersocialcredential'),
        ),
    ]
