# Generated by Django 4.0.7 on 2022-11-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0084_socialpost_post_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='auto_time',
        ),
    ]
