# Generated by Django 4.0.7 on 2022-11-29 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0085_remove_socialpost_auto_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='link_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.sociallinkfilter'),
        ),
    ]
