# Generated by Django 4.0.7 on 2022-11-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0086_socialpost_link_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
