# Generated by Django 4.0.7 on 2022-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0087_alter_pageview_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialcredential',
            name='expiration_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
