# Generated by Django 4.0.7 on 2022-12-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0088_usersocialcredential_expiration_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('subject', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('from_address', models.CharField(max_length=255)),
                ('created_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.CharField(max_length=255)),
                ('provider_message_key', models.CharField(max_length=80)),
                ('processed_dt', models.DateTimeField(blank=True, null=True)),
                ('error_dt', models.DateTimeField(blank=True, null=True)),
                ('delivered_dt', models.DateTimeField(blank=True, null=True)),
                ('opened_dt', models.DateTimeField(blank=True, null=True)),
                ('clicked_dt', models.DateTimeField(blank=True, null=True)),
                ('error_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='jvapp.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='jvapp.message')),
            ],
        ),
    ]
