# Generated by Django 4.0.7 on 2022-12-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0089_message_messagerecipient_messageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecipient',
            name='provider_message_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
