# Generated by Django 4.0.7 on 2022-12-10 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0090_alter_messagerecipient_provider_message_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='MessageThreadContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.employerjob')),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_thread_context', to='jvapp.jobapplication')),
                ('message_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jvapp.messagethread')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='message_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message', to='jvapp.messagethread'),
        ),
    ]
