# Generated by Django 4.0.7 on 2022-12-10 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0091_messagethread_messagethreadcontext_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_dt',)},
        ),
        migrations.AlterField(
            model_name='messagethreadcontext',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_thread_context', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagethreadcontext',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_thread_context', to='jvapp.employerjob'),
        ),
        migrations.AlterField(
            model_name='messagethreadcontext',
            name='message_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_thread_context', to='jvapp.messagethread'),
        ),
    ]
