# Generated by Django 4.0.7 on 2022-12-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0092_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='notification_ats_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notification_email_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
