# Generated by Django 4.0.7 on 2022-12-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0093_jobapplication_notification_ats_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='notification_ats_failure_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notification_ats_failure_msg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notification_email_failure_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
