# Generated by Django 4.0.7 on 2022-12-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0094_jobapplication_notification_ats_failure_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethreadcontext',
            name='message_thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_thread_context', to='jvapp.messagethread'),
        ),
    ]
