# Generated by Django 4.0.7 on 2022-12-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0096_usernotificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='recipient_type',
            field=models.CharField(default='to', max_length=3),
        ),
    ]
