# Generated by Django 4.0.7 on 2022-12-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0098_remove_messagethread_employer_message_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback_know_applicant',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='feedback_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='feedback_recommend_any_job',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='feedback_recommend_this_job',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
