# Generated by Django 4.0.7 on 2022-12-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0100_rename_feedback_notes_jobapplication_feedback_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='device_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
