# Generated by Django 4.0.7 on 2022-12-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0101_alter_pageview_device_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialplatform',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='socialplatform',
            name='sort_order',
            field=models.SmallIntegerField(default=1),
        ),
    ]
