# Generated by Django 4.0.7 on 2022-12-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0102_alter_socialplatform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialplatform',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
