# Generated by Django 4.0.7 on 2023-01-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0103_socialplatform_is_displayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('created_dt', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='provider_message_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
