# Generated by Django 4.0.7 on 2023-01-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0105_employerats_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerats',
            name='is_webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerats',
            name='webhook_archive_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerats',
            name='webhook_archive_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerats',
            name='webhook_delete_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerats',
            name='webhook_delete_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerats',
            name='webhook_hire_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerats',
            name='webhook_hire_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerats',
            name='webhook_stage_change_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerats',
            name='webhook_stage_change_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='salary_interval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(blank=True, default='applied', max_length=30),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_status_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
