# Generated by Django 4.0.7 on 2023-01-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0106_employerats_is_webhook_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerats',
            name='access_token',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='employerats',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
    ]
