# Generated by Django 4.0.7 on 2023-01-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0107_alter_employerats_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='ats_application_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
