# Generated by Django 4.0.7 on 2023-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0108_alter_jobapplication_ats_application_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='has_job_scrape_failure',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='has_job_scraper',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='last_job_scrape_success_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
