# Generated by Django 4.0.7 on 2023-02-11 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0110_employer_is_manual_job_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinkfilter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
