# Generated by Django 4.0.7 on 2023-02-11 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0111_alter_sociallinkfilter_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerJobSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jvapp.employer')),
                ('filter_city', models.ManyToManyField(to='jvapp.city')),
                ('filter_country', models.ManyToManyField(to='jvapp.country')),
                ('filter_job', models.ManyToManyField(to='jvapp.employerjob')),
                ('filter_state', models.ManyToManyField(to='jvapp.state')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
    ]
