# Generated by Django 4.0.7 on 2023-02-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0112_employerjobsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinkfilter',
            name='shared_by_employer_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
