# Generated by Django 4.0.7 on 2023-02-16 05:04

from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0113_sociallinkfilter_shared_by_employer_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerreferralbonusrule',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus_rule', to='jvapp.employer'),
        ),
        migrations.CreateModel(
            name='EmployerReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('cities', models.ManyToManyField(to='jvapp.city')),
                ('countries', models.ManyToManyField(to='jvapp.country')),
                ('departments', models.ManyToManyField(to='jvapp.jobdepartment')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_request', to='jvapp.employer')),
                ('jobs', models.ManyToManyField(to='jvapp.employerjob')),
                ('states', models.ManyToManyField(to='jvapp.state')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
        migrations.AddField(
            model_name='messagethreadcontext',
            name='referral_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_thread_context', to='jvapp.employerreferralrequest'),
        ),
    ]
