# Generated by Django 4.0.7 on 2023-02-17 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jvapp.models._customDjangoField


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0114_alter_employerreferralbonusrule_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', jvapp.models._customDjangoField.LowercaseCharField(max_length=20)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jvapp.employer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner_id', 'tag_name'), ('employer_id', 'tag_name')},
            },
        ),
        migrations.AddField(
            model_name='sociallinkfilter',
            name='tags',
            field=models.ManyToManyField(to='jvapp.sociallinktag'),
        ),
    ]
