# Generated by Django 4.0.7 on 2023-02-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0115_sociallinktag_sociallinkfilter_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinkfilter',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
