# Generated by Django 4.0.7 on 2023-02-20 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0116_sociallinkfilter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinktag',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jvapp.employer'),
        ),
        migrations.AlterField(
            model_name='sociallinktag',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
