# Generated by Django 4.0.7 on 2023-02-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0117_alter_sociallinktag_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinkfilter',
            name='shared_by_employer_dt',
        ),
        migrations.AddField(
            model_name='sociallinkfilter',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
