# Generated by Django 4.0.7 on 2023-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0118_remove_sociallinkfilter_shared_by_employer_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='organization_type',
            field=models.SmallIntegerField(default=1),
        ),
    ]
