# Generated by Django 4.0.7 on 2023-02-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0119_employer_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjobsubscription',
            name='filter_department',
            field=models.ManyToManyField(to='jvapp.jobdepartment'),
        ),
        migrations.AddField(
            model_name='employerjobsubscription',
            name='filter_employer',
            field=models.ManyToManyField(to='jvapp.employer'),
        ),
        migrations.AlterField(
            model_name='employerjobsubscription',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_subscription', to='jvapp.employer'),
        ),
    ]
