# Generated by Django 4.0.7 on 2023-02-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0120_employerjobsubscription_filter_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjobsubscription',
            name='filter_remote_type_bit',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
