# Generated by Django 4.0.7 on 2023-03-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0121_employerjobsubscription_filter_remote_type_bit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerjob',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
