# Generated by Django 4.0.7 on 2023-03-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0122_alter_employerjob_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_use_job_url',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
