# Generated by Django 4.0.7 on 2023-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0123_employer_is_use_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_external_application',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
