# Generated by Django 4.0.7 on 2023-03-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0124_jobapplication_is_external_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinkfilter',
            name='remote_type_bit',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
