# Generated by Django 4.0.7 on 2023-03-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0125_sociallinkfilter_remote_type_bit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicationtemplate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
