# Generated by Django 4.0.7 on 2023-03-23 18:58

import django.core.validators
from django.db import migrations, models
import jvapp.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0127_alter_employerjob_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='academic_transcript',
            field=models.FileField(blank=True, null=True, upload_to=jvapp.models.user.get_user_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'txt', 'rtf'])]),
        ),
        migrations.AddField(
            model_name='jobapplicationtemplate',
            name='academic_transcript',
            field=models.FileField(blank=True, null=True, upload_to=jvapp.models.user.get_user_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'txt', 'rtf'])]),
        ),
    ]
