# Generated by Django 4.0.7 on 2023-03-23 20:36

from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0128_jobapplication_academic_transcript_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerJobApplicationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('application_field', models.CharField(max_length=25)),
                ('is_required', models.BooleanField()),
                ('is_optional', models.BooleanField()),
                ('is_hidden', models.BooleanField()),
                ('is_locked', models.BooleanField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_requirement', to='jvapp.employer')),
                ('filter_departments', models.ManyToManyField(to='jvapp.jobdepartment')),
                ('filter_jobs', models.ManyToManyField(to='jvapp.employerjob')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
    ]
