# Generated by Django 4.0.7 on 2023-03-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0130_add_application_requirements'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employerjobapplicationrequirement',
            unique_together={('employer', 'application_field', 'is_required', 'is_optional', 'is_hidden')},
        ),
    ]
