# Generated by Django 4.0.7 on 2023-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0131_alter_employerjobapplicationrequirement_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicationtemplate',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
