# Generated by Django 4.0.7 on 2023-04-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0133_userapplicationreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userapplicationreview',
            unique_together={('user', 'application')},
        ),
    ]
