# Generated by Django 4.0.7 on 2023-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0135_usersocialcredential_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployercandidate',
            name='ats_candidate_key',
            field=models.CharField(max_length=100),
        ),
    ]
