# Generated by Django 4.0.7 on 2023-04-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0137_messagethread_external_thread_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_message_key',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
