# Generated by Django 4.0.7 on 2023-04-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0139_employerslack'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerslack',
            name='jobs_post_dow_bits',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerslack',
            name='jobs_post_max_jobs',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerslack',
            name='jobs_post_tod',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
