# Generated by Django 4.0.7 on 2023-04-24 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0140_employerslack_jobs_post_dow_bits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('channel', models.CharField(max_length=30)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to='jvapp.employer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to='jvapp.employerjob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.UniqueConstraint(condition=models.Q(('user', None)), fields=('employer', 'job', 'channel'), name='unique_employer_job_channel'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.UniqueConstraint(condition=models.Q(('employer', None)), fields=('user', 'job', 'channel'), name='unique_user_job_channel'),
        ),
    ]
