# Generated by Django 4.0.7 on 2023-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0142_remove_employerslack_jobs_post_tod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerslack',
            name='referrals_post_channel',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
