# Generated by Django 4.0.7 on 2023-04-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0143_employerslack_referrals_post_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
