# Generated by Django 4.0.7 on 2023-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0144_jobvyneuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerslack',
            name='enterprise_key',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerslack',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
