# Generated by Django 4.0.7 on 2023-04-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0145_employerslack_enterprise_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerslack',
            name='team_key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employerslack',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerslack',
            name='enterprise_key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
