# Generated by Django 4.0.7 on 2023-05-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0146_employerslack_team_key_employerslack_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjobsubscription',
            name='filter_job_title_regex',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
