# Generated by Django 4.0.7 on 2023-05-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0147_employerjobsubscription_filter_job_title_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjobsubscription',
            name='filter_exclude_job_title_regex',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
