# Generated by Django 4.0.7 on 2023-05-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0148_employerjobsubscription_filter_exclude_job_title_regex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerjobsubscription',
            name='filter_department',
        ),
    ]
