# Generated by Django 4.0.7 on 2023-05-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0149_remove_employerjobsubscription_filter_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='days_after_hire_payout',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
