# Generated by Django 4.0.7 on 2023-05-22 00:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract
import jvapp.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0150_employer_days_after_hire_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='donation_organizations')),
                ('url_main', models.CharField(blank=True, max_length=100, null=True)),
                ('url_donation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_dt', models.DateTimeField()),
                ('donation_receipt', models.FileField(blank=True, null=True, upload_to=jvapp.models.user.get_user_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'txt', 'rtf', 'png', 'jpeg', 'jpg', 'gif'])])),
                ('is_verified', models.BooleanField(default=False)),
                ('donation_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donation', to='jvapp.donationorganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
        migrations.CreateModel(
            name='UserDonationOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='jvapp.donationorganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'donation_organization')},
            },
        ),
    ]
