# Generated by Django 4.0.7 on 2023-05-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0151_donationorganization_userdonation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonation',
            name='donation_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
