# Generated by Django 4.0.7 on 2023-05-29 21:57

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0151_location_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerjobsubscription',
            name='filter_city',
        ),
        migrations.RemoveField(
            model_name='employerjobsubscription',
            name='filter_country',
        ),
        migrations.RemoveField(
            model_name='employerjobsubscription',
            name='filter_state',
        ),
        migrations.RemoveField(
            model_name='employerreferralrequest',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='employerreferralrequest',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='employerreferralrequest',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='employerreferralrequest',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='employerreferralrequest',
            name='states',
        ),
        migrations.RemoveField(
            model_name='sociallinkfilter',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='sociallinkfilter',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='sociallinkfilter',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='sociallinkfilter',
            name='states',
        ),
        migrations.AddField(
            model_name='employerjobsubscription',
            name='filter_location',
            field=models.ManyToManyField(to='jvapp.location'),
        ),
        migrations.AddField(
            model_name='employerjobsubscription',
            name='filter_range_miles',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
