# Generated by Django 4.0.7 on 2023-05-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0152_userdonation_donation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonation',
            name='donation_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdonation',
            name='donation_amount_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jvapp.currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdonation',
            name='donation_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_donation', to='jvapp.donationorganization'),
        ),
    ]
