# Generated by Django 4.0.7 on 2023-05-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0153_userdonation_donation_amount_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE jvapp_userdonation DROP FOREIGN KEY jvapp_userdonation_donation_amount_curr_c0320d8c_fk_jvapp_cur;'
            ],
        ),
    ]
