# Generated by Django 4.0.7 on 2023-05-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0153_alter_locationlookup_raw_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
