# Generated by Django 4.0.7 on 2023-05-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0153_userdonation_donation_amount_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'DROP INDEX jvapp_userdonation_donation_amount_curr_c0320d8c_fk_jvapp_cur ON jvapp_userdonation;'
                'ALTER TABLE jvapp_userdonation ADD CONSTRAINT jvapp_userdonation_donation_amount_curr_c0320d8c_fk_jvapp_cur foreign key (donation_amount_currency_id) references jvapp_currency (name);'
            ],
        ),
    ]
