# Generated by Django 4.0.7 on 2023-05-30 16:18
from PIL import Image
from django.core.files import File
from django.db import migrations, models
import jvapp.models.employer
from jvapp.utils.file import get_file_extension, get_file_name
from jvapp.utils.image import resize_image_with_fill


def convert_images(apps, schema_editor):
    Employer = apps.get_model('jvapp', 'Employer')
    for employer in Employer.objects.all():
        if not (employer_logo := employer.logo):
            continue
        new_image = resize_image_with_fill(employer_logo, 88, 88)
        if not new_image:
            continue
        file_name = get_file_name(employer_logo.url, is_include_extension=False)
        file_extension = get_file_extension(employer_logo.url)
        employer.logo_square_88 = File(new_image, name=f'{file_name}_square_88.{file_extension}')
        employer.save()
        new_image.close()


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0154_alter_location_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='logo_square_88',
            field=models.ImageField(blank=True, null=True, upload_to=jvapp.models.employer.get_employer_upload_location),
        ),
        migrations.RunPython(convert_images, atomic=True)
    ]
