# Generated by Django 4.0.7 on 2023-05-24 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jvapp.models.abstract
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0155_alter_userdonation_donation_amount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=25)),
                ('connection_first_name', models.CharField(max_length=150)),
                ('connection_last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('connection_linkedin_url', models.CharField(blank=True, max_length=200, null=True)),
                ('connection_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('connection_phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('connector_first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('connector_last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('connector_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('connector_phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('request_data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, jvapp.models.abstract.JobVynePermissionsMixin),
        ),
    ]
