# Generated by Django 4.0.7 on 2023-05-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0155_employer_logo_square_88'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployerPage',
        ),
    ]
