# Generated by Django 4.0.7 on 2023-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0156_userrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
