# Generated by Django 4.0.7 on 2023-05-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0156_delete_employerpage'),
        ('jvapp', '0157_alter_userrequest_request_data'),
    ]

    operations = [
    ]
