# Generated by Django 4.0.7 on 2023-05-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0158_merge_20230531_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationorganization',
            name='ein',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donationorganization',
            name='every_org_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
