# Generated by Django 4.0.7 on 2023-06-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0159_donationorganization_ein_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationorganization',
            name='url_donation',
        ),
        migrations.AddField(
            model_name='donationorganization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
