# Generated by Django 4.2.1 on 2023-06-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0162_jobvyneuser_linkedin_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerJobSubscription',
            new_name='JobSubscription',
        ),
    ]
