# Generated by Django 4.2.1 on 2023-06-06 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0163_rename_employerjobsubscription_jobsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubscription',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='jobsubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobsubscription',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_subscription', to='jvapp.employer'),
        ),
    ]
