# Generated by Django 4.2.1 on 2023-06-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0164_remove_jobsubscription_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubscription',
            name='title',
            field=models.CharField(default='General', max_length=200),
            preserve_default=False,
        ),
    ]
