# Generated by Django 4.2.1 on 2023-06-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0167_rename_sociallinkfilter_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubscription',
            name='is_single_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='jobsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_single_employer', True)), fields=('employer',), name='unique_employer'),
        ),
    ]
