# Generated by Django 4.2.1 on 2023-06-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0169_employer_job_subscriptions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sociallinktag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sociallinktag',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='sociallinktag',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='tags',
        ),
        migrations.AddField(
            model_name='jobsubscription',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_subscription', to='jvapp.employerjob', unique=True),
        ),
        migrations.AddConstraint(
            model_name='sociallink',
            constraint=models.UniqueConstraint(condition=models.Q(('employer__isnull', False), ('owner__isnull', False)), fields=('employer', 'owner'), name='unique_employer_owner'),
        ),
        migrations.DeleteModel(
            name='SocialLinkTag',
        ),
    ]
