# Generated by Django 4.2.1 on 2023-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0170_alter_sociallinktag_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='is_primary',
        ),
        migrations.AddConstraint(
            model_name='sociallink',
            constraint=models.UniqueConstraint(condition=models.Q(('employer__isnull', True), ('is_default', True), ('owner__isnull', False)), fields=('is_default', 'owner'), name='unique_owner_default'),
        ),
        migrations.AddConstraint(
            model_name='sociallink',
            constraint=models.UniqueConstraint(condition=models.Q(('employer__isnull', False), ('is_default', True), ('owner__isnull', True)), fields=('is_default', 'employer'), name='unique_employer_default'),
        ),
    ]
