# Generated by Django 4.2.1 on 2023-06-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0175_fix_existing_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
