# Generated by Django 4.2.1 on 2023-06-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0176_alter_sociallink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locationlookup',
            name='text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
