# Generated by Django 4.2.1 on 2023-06-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0177_alter_location_text_alter_locationlookup_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='social_link_filter',
            new_name='social_link',
        ),
        migrations.RenameField(
            model_name='pageview',
            old_name='social_link_filter',
            new_name='social_link',
        ),
        migrations.RenameField(
            model_name='socialpost',
            old_name='link_filter',
            new_name='social_link',
        ),
    ]
