# Generated by Django 4.2.1 on 2023-06-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0178_rename_social_link_filter_jobapplication_social_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='social_platform',
        ),
    ]
