# Generated by Django 4.2.1 on 2023-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0179_remove_socialpost_social_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='formatted_content',
        ),
        migrations.AddField(
            model_name='socialpostaudit',
            name='formatted_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
