# Generated by Django 4.2.1 on 2023-06-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0180_remove_socialpost_formatted_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('provider', models.CharField(max_length=32)),
                ('subscription_type', models.CharField(max_length=40)),
                ('subscription_data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider', 'subscription_type')},
            },
        ),
    ]
