# Generated by Django 4.2.1 on 2023-06-28 16:02
import django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0181_usersocialsubscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobpost',
            name='unique_user_job_channel',
        ),
        migrations.RemoveConstraint(
            model_name='jobpost',
            name='unique_employer_job_channel',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='recipient_job_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
