# Generated by Django 4.2.1 on 2023-06-28 16:02
import django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0182_rename_user_jobpost_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.UniqueConstraint(condition=models.Q(('owner', None), ('recipient', None)),
                                               fields=('employer', 'job', 'channel'),
                                               name='unique_employer_job_channel'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.UniqueConstraint(condition=models.Q(('employer', None), ('recipient', None)),
                                               fields=('owner', 'job', 'channel'), name='unique_owner_job_channel'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.UniqueConstraint(condition=models.Q(('employer', None), ('owner', None)),
                                               fields=('recipient', 'job', 'channel'),
                                               name='unique_recipient_job_channel'),
        ),
    ]
