# Generated by Django 4.0.7 on 2023-06-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0157_taxtype_taxonomy_jobtaxonomy_and_more'),
        ('jvapp', '0183_add_jobpost_constraints'),
    ]

    operations = [
    ]
