# Generated by Django 4.2.1 on 2023-06-28 21:37

from django.db import migrations, models

from jvapp.utils.taxonomy import update_taxonomies


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0184_merge_20230628_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='tax_type',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='TaxType',
        ),
        migrations.RunPython(update_taxonomies)
    ]
