# Generated by Django 4.2.1 on 2023-06-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0185_alter_taxonomy_tax_type_delete_taxtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
