# Generated by Django 4.2.1 on 2023-06-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0186_taxonomy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='qualifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='responsibilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='technical_qualifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
