# Generated by Django 4.2.1 on 2023-06-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0187_employerjob_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtaxonomy',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy', to='jvapp.employerjob'),
        ),
    ]
