# Generated by Django 4.0.7 on 2023-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0188_alter_jobtaxonomy_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('prompt_hash', models.CharField(max_length=40)),
                ('result_status', models.CharField(max_length=20)),
                ('response', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
