# Generated by Django 4.0.7 on 2023-07-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0189_airequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='prompt_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jvapp.airequest'),
        ),
    ]
