# Generated by Django 4.0.7 on 2023-07-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0190_employerjob_prompt_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerjob',
            old_name='prompt_tracker',
            new_name='qualifications_prompt',
        ),
    ]
