# Generated by Django 4.2.1 on 2023-07-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0193_alter_jobtaxonomy_job_alter_jobtaxonomy_taxonomy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubscription',
            name='filter_exclude_job_title_regex',
        ),
        migrations.RemoveField(
            model_name='jobsubscription',
            name='filter_job_title_regex',
        ),
        migrations.AddField(
            model_name='jobsubscription',
            name='filter_job_titles',
            field=models.ManyToManyField(to='jvapp.taxonomy'),
        ),
    ]
