# Generated by Django 4.2.1 on 2023-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0194_remove_jobsubscription_filter_exclude_job_title_regex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(default='General', max_length=250),
        ),
    ]
