# Generated by Django 4.2.1 on 2023-07-07 19:32
import re

from django.db import migrations, models


def make_safe_key(apps, schema_editor):
    employer_model = apps.get_model('jvapp', 'Employer')
    employers_to_update = {}
    for employer in employer_model.objects.all():
        employer.employer_key = re.sub('[^a-z0-9]', '-', employer.employer_name.lower())
        if employers_to_update.get(employer.employer_key):
            employer.employer_key = f'{employer.employer_key}{employer.id}'
        employers_to_update[employer.employer_key] = employer
    
    employer_model.objects.bulk_update(list(employers_to_update.values()), ['employer_key'])
    

class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0195_alter_sociallink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.RunPython(make_safe_key, atomic=True)
    ]
