# Generated by Django 4.2.1 on 2023-07-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0196_employer_employer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
