# Generated by Django 4.2.1 on 2023-07-09 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0197_taxonomy_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_view', to='jvapp.employer'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='page_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
