# Generated by Django 4.2.1 on 2023-07-09 17:47

from django.db import migrations, models
import django.db.models.deletion


def parse_social_links(apps, schema_editor):
    job_application_model = apps.get_model('jvapp', 'JobApplication')
    job_apps = job_application_model.objects\
        .select_related('social_link')\
        .filter(social_link__isnull=False)
    
    for job_app in job_apps:
        job_app.referrer_employer_id = job_app.social_link.employer_id
        job_app.referrer_user_id = job_app.social_link.owner_id
    
    job_application_model.objects.bulk_update(list(job_apps), ['referrer_employer_id', 'referrer_user_id'])
    
    
def parse_page_views(apps, schema_editor):
    page_view_model = apps.get_model('jvapp', 'PageView')
    page_views = page_view_model.objects \
        .select_related('social_link') \
        .filter(social_link__isnull=False)
    
    for page_view in page_views:
        page_view.employer_id = page_view.social_link.employer_id
        page_view.page_owner_id = page_view.social_link.owner_id
    
    page_view_model.objects.bulk_update(list(page_views), ['employer_id', 'page_owner_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0199_jobapplication_referrer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='referrer',
            new_name='referrer_user',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='referrer_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='jvapp.employer'),
        ),
        migrations.RunPython(parse_social_links),
        migrations.RunPython(parse_page_views),
    ]
