# Generated by Django 4.2.1 on 2023-07-18 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0201_cleanup_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='is_job_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_job', to='jvapp.employer'),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_job', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_job', to='jvapp.employer'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='social_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_view', to='jvapp.sociallink'),
        ),
    ]
