# Generated by Django 4.2.1 on 2023-07-18 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0202_employerjob_is_job_approved_employerjob_source_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerjob',
            name='source_group',
        ),
        migrations.RemoveField(
            model_name='employerjob',
            name='source_user',
        ),
        migrations.CreateModel(
            name='EmployerJobConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('connection_type', models.SmallIntegerField()),
                ('is_allow_contact', models.BooleanField()),
                ('is_job_creator', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_connection', to='jvapp.employer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_connection', to='jvapp.employerjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='employerjobconnection',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_user_job'),
        ),
    ]
