# Generated by Django 4.2.1 on 2023-07-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0203_remove_employerjob_source_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_employer_approved',
            field=models.BooleanField(default=True),
        ),
    ]
