# Generated by Django 4.2.1 on 2023-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0204_employer_is_employer_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerjobconnection',
            name='group',
        ),
        migrations.AddField(
            model_name='jobsubscription',
            name='is_user_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='jobsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_user_entered', True)), fields=('employer',), name='unique_user_provided_jobs'),
        ),
    ]
