# Generated by Django 4.2.1 on 2023-07-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0206_jobpost_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='ownership_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='size_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='size_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='year_founded',
            field=models.IntegerField(null=True),
        ),
    ]
