# Generated by Django 4.2.1 on 2023-07-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0207_employer_description_employer_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='employer_size',
        ),
        migrations.DeleteModel(
            name='EmployerSize',
        ),
    ]
