# Generated by Django 4.2.1 on 2023-07-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0208_remove_employer_employer_size_delete_employersize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('linkedin_handle', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('size_min', models.SmallIntegerField(blank=True, null=True)),
                ('size_max', models.SmallIntegerField(blank=True, null=True)),
                ('company_type', models.CharField(blank=True, max_length=20, null=True)),
                ('founded_year', models.SmallIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
