# Generated by Django 4.2.1 on 2023-08-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0210_remove_employer_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='home_post_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='job_search_type_bit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='membership_employers',
            field=models.ManyToManyField(related_name='employer_member', to='jvapp.employer'),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='membership_groups',
            field=models.ManyToManyField(related_name='group_member', to='jvapp.employer'),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='membership_professions',
            field=models.ManyToManyField(related_name='profession_member', to='jvapp.taxonomy'),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='work_remote_type_bit',
            field=models.SmallIntegerField(default=3),
        ),
    ]
