# Generated by Django 4.2.1 on 2023-08-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0211_jobvyneuser_home_post_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='is_job_search_visible',
            field=models.BooleanField(default=False),
        ),
    ]
