# Generated by Django 4.2.1 on 2023-08-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0212_jobvyneuser_is_job_search_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsubscription',
            old_name='filter_job_titles',
            new_name='filter_job_professions',
        ),
    ]
