# Generated by Django 4.2.1 on 2023-08-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0213_rename_filter_job_titles_jobsubscription_filter_job_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='sort_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
