# Generated by Django 4.2.1 on 2023-08-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0214_taxonomy_sort_order_alter_taxonomy_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='job_search_industries',
            field=models.ManyToManyField(related_name='industry_job_seeker', to='jvapp.taxonomy'),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='job_search_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_job_seeker', to='jvapp.taxonomy'),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='job_search_professions',
            field=models.ManyToManyField(related_name='profession_job_seeker', to='jvapp.taxonomy'),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='job_search_qualifications',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobvyneuser',
            name='professional_site_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
