# Generated by Django 4.2.1 on 2023-08-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0215_jobvyneuser_job_search_industries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='is_employer_approved',
        ),
        migrations.AddField(
            model_name='employer',
            name='is_user_created',
            field=models.BooleanField(default=False),
        ),
    ]
