# Generated by Django 4.2.1 on 2023-08-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0216_remove_employer_is_employer_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerjobconnection',
            name='is_job_creator',
        ),
    ]
