# Generated by Django 4.2.1 on 2023-08-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0218_jobvyneuser_job_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobvyneuser',
            old_name='job_department',
            new_name='profession',
        ),
    ]
