# Generated by Django 4.2.1 on 2023-08-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0219_rename_job_department_jobvyneuser_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerjob',
            name='close_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='open_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
