# Generated by Django 4.2.1 on 2023-08-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0221_alter_city_name_alter_country_name_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerjob',
            name='is_job_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
