# Generated by Django 4.2.1 on 2023-08-16 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0208_article'),
        ('jvapp', '0222_alter_employerjob_is_job_approved'),
    ]

    operations = [
    ]
