# Generated by Django 4.2.1 on 2023-08-11 19:11
import logging

from django.db import migrations

from jvapp.apis.geocoding import LocationParser

logger = logging.getLogger(__name__)

def add_user_location(apps, schema_editor):
    location_parser = LocationParser()
    user_model = apps.get_model('jvapp', 'JobVyneUser')
    users = user_model.objects.filter(home_post_code__isnull=False, home_location__isnull=True)
    for user in users:
        home_location = location_parser.get_location(user.home_post_code, is_zip_code=True)
        user.home_location_id = home_location.id
    user_model.objects.bulk_update(users, ['home_location_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0223_alter_location_unique_together_location_postal_code_and_more'),
    ]

    operations = [
        migrations.RunPython(add_user_location, atomic=True),
        migrations.RemoveField(
            model_name='jobvyneuser',
            name='home_post_code',
        ),
    ]
