# Generated by Django 4.2.1 on 2023-08-14 13:54

from django.db import migrations, models

from jvapp.models import JobVyneUser


def migrate_search_levels(apps, schema_editor):
    user_model = apps.get_model('jvapp', 'JobVyneUser')
    user_job_level_map = {
        user.id: user.job_search_level.id for user in
        user_model.objects.select_related('job_search_level').filter(job_search_level__isnull=False)
    }
    users = JobVyneUser.objects.filter(id__in=list(user_job_level_map.keys()))
    for user in users:
        user.job_search_levels.add(user_job_level_map[user.id])


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0224_remove_jobvyneuser_home_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='job_search_levels',
            field=models.ManyToManyField(related_name='levels_job_seeker', to='jvapp.taxonomy'),
        ),
        migrations.RunPython(migrate_search_levels, atomic=True),
    ]
