# Generated by Django 4.2.1 on 2023-08-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0225_jobvyneuser_job_search_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvyneuser',
            name='job_search_level',
        ),
        migrations.AlterField(
            model_name='jobvyneuser',
            name='job_search_levels',
            field=models.ManyToManyField(related_name='level_job_seeker', to='jvapp.taxonomy'),
        ),
    ]
