# Generated by Django 4.2.1 on 2023-08-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0226_remove_jobvyneuser_job_search_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='job_description_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
