# Generated by Django 4.2.1 on 2023-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0228_pageview_viewer_alter_pageview_employer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employerjob',
            index=models.Index(models.F('open_date'), models.F('id'), name='open_date_id_idx'),
        ),
    ]
