# Generated by Django 4.2.1 on 2023-08-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0232_employerjob_job_key_step3'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='sub_taxonomies',
            field=models.ManyToManyField(to='jvapp.taxonomy'),
        ),
    ]
