# Generated by Django 4.2.1 on 2023-08-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0233_taxonomy_sub_taxonomies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='sub_taxonomies',
            field=models.ManyToManyField(related_name='parent_taxonomy', to='jvapp.taxonomy'),
        ),
    ]
