# Generated by Django 4.2.1 on 2023-08-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0234_alter_taxonomy_sub_taxonomies'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubscription',
            name='filter_is_salary_only',
            field=models.BooleanField(default=False),
        ),
    ]
