# Generated by Django 4.2.1 on 2023-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0237_applicanttrackingsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanttrackingsystem',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
