# Generated by Django 4.2.1 on 2023-08-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0238_alter_applicanttrackingsystem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerjob',
            options={'ordering': ('-open_date', 'id')},
        ),
    ]
