# Generated by Django 4.2.1 on 2023-08-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0239_alter_employerjob_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerjob',
            options={'ordering': ('-open_date', '-id')},
        ),
    ]
