# Generated by Django 4.2.1 on 2023-09-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0224_article_companies_article_industries_and_more'),
        ('jvapp', '0240_alter_employerjob_options'),
    ]

    operations = [
    ]
