# Generated by Django 4.2.1 on 2023-08-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0241_userslackprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslackprofile',
            name='team_key',
            field=models.CharField(default='bogus', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userslackprofile',
            name='user_key',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='userslackprofile',
            constraint=models.UniqueConstraint(fields=('user_key', 'team_key'), name='unique_user'),
        ),
    ]
