# Generated by Django 4.2.1 on 2023-09-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0244_alter_jobtaxonomy_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
