# Generated by Django 4.2.1 on 2023-09-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0246_employerjob_approval_and_date_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employerjob',
            name='approval_and_date_idx',
        ),
        migrations.AddIndex(
            model_name='employerjob',
            index=models.Index(models.F('close_date'), models.F('open_date'), name='open_close_idx'),
        ),
    ]
