# Generated by Django 4.2.1 on 2023-09-02 19:39
import re

from django.db import migrations, models

from jvapp.models import JobVyneUser


def make_safe_key(apps, schema_editor):
    users_to_update = {}
    for user in JobVyneUser.objects.all():
        if user.full_name:
            user.user_key = re.sub('[^a-z0-9]', '-', user.full_name.lower())
            if users_to_update.get(user.user_key):
                user.user_key = f'{user.user_key}{user.id}'
        else:
            user.user_key = f'user-{user.id}'
        users_to_update[user.user_key] = user
    
    JobVyneUser.objects.bulk_update(list(users_to_update.values()), ['user_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0247_remove_employerjob_approval_and_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='user_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.RunPython(make_safe_key)
    ]
