# Generated by Django 4.2.1 on 2023-09-03 00:07

from django.db import migrations, models

from jvapp.models.employer import EmployerConnection


def consolidate_connections(apps, schema_editor):
    employer_connections = EmployerConnection.objects.all()
    mapped_connections = {}
    for connection in employer_connections:
        connection_key = (connection.employer_id, connection.user_id)
        existing_connection = mapped_connections.get(connection_key)
        if existing_connection:
            connection.delete()
        else:
            mapped_connections[connection_key] = connection


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0249_userconnection_employerconnection_and_more'),
    ]

    operations = [
        migrations.RunPython(consolidate_connections),
        migrations.RemoveConstraint(
            model_name='employerconnection',
            name='unique_employer_connection',
        ),
        migrations.AddConstraint(
            model_name='employerconnection',
            constraint=models.UniqueConstraint(fields=('user', 'employer'), name='unique_employer_connection'),
        ),
    ]
