# Generated by Django 4.2.1 on 2023-09-06 15:25

from django.db import migrations
import jvapp.models._customDjangoField


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0251_jobapplication_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_name_aliases',
            field=jvapp.models._customDjangoField.SeparatedValueField('|', blank=True, max_length=200, null=True),
        ),
    ]
