# Generated by Django 4.2.1 on 2023-09-07 17:34

from django.db import migrations

from jvapp.models.employer import Employer


def update_employers(apps, schema_editor):
    employers = Employer.objects.all()
    for employer in employers:
        employer.industry = None
        employer.ownership_type = None
        employer.size_min = None
        employer.size_max = None
        employer.website = None
        employer.year_founded = None
        employer.linkedin_handle = None
    Employer.objects.bulk_update(employers, [
        'industry', 'ownership_type', 'size_min', 'size_max', 'website', 'year_founded', 'linkedin_handle'
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0252_employer_employer_name_aliases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalCompanyData',
        ),
        migrations.RunPython(update_employers)
    ]
