# Generated by Django 4.2.1 on 2023-09-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0253_delete_externalcompanydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvyneuser',
            name='is_share_connections',
            field=models.BooleanField(default=True),
        ),
    ]
