# Generated by Django 4.2.1 on 2023-09-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0241_merge_20230906_1403'),
        ('jvapp', '0254_jobvyneuser_is_share_connections'),
    ]

    operations = [
    ]
