# Generated by Django 4.2.1 on 2023-09-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0255_merge_20230912_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('source', models.CharField(max_length=40)),
                ('source_url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jvapp.employer')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jvapp.location')),
                ('professions', models.ManyToManyField(related_name='profession_events', to='jvapp.taxonomy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
