# Generated by Django 4.2.1 on 2023-09-13 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0256_emailunsubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_email', models.EmailField(max_length=254)),
                ('sent_dt', models.DateTimeField()),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='useremailinvite',
            constraint=models.UniqueConstraint(fields=('invite_email', 'inviter_id'), name='unique_invite'),
        ),
    ]
