# Generated by Django 4.2.1 on 2023-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvapp', '0257_useremailinvite_useremailinvite_unique_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailunsubscribe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
